version: '2'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
       - "4100:4000"
    depends_on:
    - mongo
    env_file: .env
    environment:
      - DB_URI=$DB_URI
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes: 
    - mongo-volume:/data/db
volumes: 
  mongo-volume:
